export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const ADD_CAMERA_ROLL_ROW = 'ADD_CAMERA_ROLL_ROW';
export const SET_SELECTED_IMAGES = 'SET_SELECTED_IMAGES';
export const SET_NUM_FINISHED = 'SET_NUM_FINISHED';
export const SET_PROGRESSES = 'SET_PROGRESSES';
export const SET_TOTALS = 'SET_TOTALS';
export const SET_NUM_TO_UPLOAD = 'SET_NUM_TO_UPLOAD';
export const SET_IS_UPLOADING = 'SET_IS_UPLOADING';
