# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photoapplication' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photoapplication

  target 'photoapplication-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'photoapplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'photoapplication-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photoapplication-tvOS

  target 'photoapplication-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
